### PR TITLE
Fix Travis CI tests

### PR DESCRIPTION
**Pull request by torfsen**
See https://docs.travis-ci.com/user/ci-environment/.

### CODE REVIEW

**Comment by k-nut** [comment]
@torfsen nice! I think now the build is failing because of some changes in solr though. I recently fixed the build for `ckanext-datapackager` and I think this is related to the `travis-run.sh` file.

Maybe you can just copy it from that project and see if it works:

https://github.com/ckan/ckanext-datapackager/blob/master/bin/travis-run.sh

**Comment by k-nut** [comment]
🎉 now it only fails for python 2.6 because we are using dict comprehension in ckan master which is not available in python 2.6. Maybe we should remove the travis run for python 2.6? Would love @amercader's opinion on this.

**Comment by amercader** [comment]
If @jqnatividad is happy I'd just drop python 2.6 support

**Comment by torfsen** [comment]
If we want to continue supporting older CKAN releases we should continue to test on Python 2.6. However we would have to update the Travis setup for that: Since CKAN `master` will drop Python 2.6 support we would need to use some of the release branches for the 2.6 tests instead.

Personally I'm fine with dropping support for 2.6 but I don't know how many sites are still using it.

**Comment by torfsen** [comment]
@jqnatividad, what's your stance on dropping support for Python 2.6?

**Comment by torfsen** [comment]
@jqnatividad ping

**Comment by torfsen** [comment]
@amercader it seems that @jqnatividad is currently busy with other things, should we go ahead and drop support for Python 2.6?

**Comment by amercader** [comment]
@torfsen yes, just remove it from the Travis matrix and mention it on the README. Thanks!

**Comment by torfsen** [comment]
@amercader I've removed support for Python 2.6 from `.travis.yml` and `setup.py` and updated `README.rst`. So this PR is ready from my point of view (and once it is merged we can finally merge #24, too, which was my goal all the time :laughing:).

**Pull request merged**
